name: Smaply
favicon: null
layout_spectrum: 0.8469647660385817
typography_spectrum: 0.6354819170664996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1343090666923672
  lightness: 0.3847486702725291
  saturation: 0.3020648853853345
  rhythmicContrast: 0.7042664475739002
purpose: []
